app: website
org: jessefarnham
service: website

provider:
    name: aws
    runtime: nodejs12.x
    environment:
      aircraftTableName: aircraft
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.aircraftTableName}"

functions:
    updateFlightInfo:
        memory: 512
        timeout: 10
        handler: code/flightinfo.update
        runtime: nodejs12.x
        events:
            - http:
                path: flightinfo
                method: post
                cors: true
    getFlightInfo:
      memory: 512
      timeout: 10
      handler: code/flightinfo.get
      runtime: nodejs12.x
      events:
        - http:
            path: flightinfo/{tailnumber}
            method: get
            cors: true
    listFlightInfos:
      memory: 512
      timeout: 10
      handler: code/flightinfo.list
      runtime: nodejs12.x
      events:
        - http:
            path: flightinfo
            method: get
            cors: true

resources:
  Resources:
    AircraftDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: tailNumber
            AttributeType: S
        KeySchema:
          - AttributeName: tailNumber
            KeyType: HASH
        TableName: ${self:provider.environment.aircraftTableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
