#!/usr/bin/env node
/**
 * Generates a module with last modified dates for source files.
 * Uses git commit timestamps to determine when files were last meaningfully changed.
 * 
 * Run this before builds: node scripts/generateLastModified.js
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Files to track - map component names to their source files
const trackedFiles = {
  'Home': 'src/containers/Home.js',
  'Contact': 'src/containers/Contact.js',
  'ReadingList': 'src/containers/ReadingList.js',
  'FlightStatus': 'src/containers/FlightStatus.js',
  'FlightPlanner': 'src/containers/FlightPlanner.js',
};

function getLastModifiedDate(filePath) {
  try {
    // Get the last commit date for this file
    const result = execSync(
      `git log -1 --format=%ci -- "${filePath}"`,
      { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }
    ).trim();
    
    if (result) {
      return new Date(result).toISOString();
    }
  } catch (error) {
    // File might not be tracked by git yet
  }
  
  // Fallback to file system modification time
  try {
    const stats = fs.statSync(filePath);
    return stats.mtime.toISOString();
  } catch (error) {
    return new Date().toISOString();
  }
}

function generate() {
  const dates = {};
  
  for (const [name, filePath] of Object.entries(trackedFiles)) {
    dates[name] = getLastModifiedDate(filePath);
  }
  
  const output = `// Auto-generated by scripts/generateLastModified.js
// Do not edit manually - this file is regenerated at build time

const lastModified = ${JSON.stringify(dates, null, 2)};

export function getLastModified(componentName) {
  const isoDate = lastModified[componentName];
  if (!isoDate) return null;
  
  return new Date(isoDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
}

export default lastModified;
`;

  const outputPath = path.join(__dirname, '..', 'src', 'lastModified.js');
  fs.writeFileSync(outputPath, output);
  console.log('Generated src/lastModified.js');
  console.log('Dates:', dates);
}

generate();
